### ISSUE TITLE
A more space-efficient protocol?

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/gyuunu#11]
At the cost of some complication in both the client and server, the protocol could be made much more space-efficient. [meguca uses a binary/json hybrid](https://github.com/bakape/meguca/blob/master/client/connection.ts#L140), #10 suggests a way to remove post IDs which can be inferred.

For example, the consider the humble "append text" message. Right now this is sent down the wire like so:

```
{"type":6,"data":"{\"post_id\":1,\"append\":\"foo bar baz\"}"}
```

62 characters! By using a two-byte prefix for the number and removing the need to escape, we get down to 38 characters:

```
06{"post_id":1,"append":"foo bar baz"}
```

We can go even shorter by dropping the post ID, 27 characters, under half the original:

```
06{"append":"foo bar baz"}
```

If we really want to squeeze out every byte we could even drop the leading `{` and trailing `}`, as they're always going to be there. An extreme example in this case would be the "close post" message, which would drop down to just the 2 bytes for the type number.

**Comment by barrucadu** [comment]
This is perhaps more important now that the "synchronise" message exists. A stringified list of messages (with stringified bits!) really does take up a lot of space just for backslashes! meguca solves that problem by using `0x00`s to separate multiple messages in the same response.

**Comment by sweetsbeats** [comment]
Those backslashes look like a complete pain to work with. The second example looked much better. Unless there is any complications with the second method I'm unaware of, we should try to use as little characters as possible

**Comment by barrucadu** [comment]
Yeah, it's implemented now. See [protocol.markdown](https://github.com/barrucadu/gyuunu/blob/master/doc/protocol.markdown).
